apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        # THREE ENV VARS
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        # THIS IS THE SAME AS IN OUR DEPLOYMENT YAML. WE use SECRETS FROM SECRET YAML
          valueFrom:
            secretKeyRef:
              # WHAT SECRET?
              name: mongodb-secret
              # WHAT THE KEY NAME IS
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password

        # FROM OUR CONFIG MAP <-- CAN USE PLAIN TEXT URL OR FROM CONFIG MAP. BETTER CUS JUT HAVE
        # TO REFERENCE VAR
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
# DEFINING EXTERNAL SERVICE
apiVersion: v1
# EXTERNAL
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      # Our access port that we access in our browser
      nodePort: 30000