apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        # From docker hub
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value:
        - name: MONGO_INITDB_ROOT_USERNAME
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
# SERVICE SPECIFICATION < -- THIS IS A INTERNAL SERVICE'
# Can create it as a seperate FILE .yaml or include it here
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
  # MATCHES TO THE POD
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
